### PR TITLE
rendom forst testing

### PR DESCRIPTION
**Pull request by tamiratGit**
two testing cases, 1 . rondom forst is done on pyspark dataframe, 2. test is done on pandas

### CODE REVIEW

**Comment by akusok** [comment]
I checked the PR, very cool to see that you took two different approaches (Spark's Random Forest and Scikit-Learn's Random Forest).

**Comment by akusok** [comment]
The first file gives correct and expected results: the data is really insufficient, but the ROC curve goes above diagonal (diagonal is "random guessing"), so the method manages to get a little bit of information even from this poor data.

**Comment by akusok** [comment]
The second file is honestly a shock to me, it works way better than I would imagine. Sure, we have over 5000 points - but predicting so well without specialised geological data is really unexpected. Well done!

**Comment by akusok** [comment]
This means we are back on the timeline for your thesis. Please check the requirements, and a couple theses of other people who got a 5, to see how much programming stuff you would need to show in the MSc thesis. The second result is great, but I would guess it is not enough, and you should show more stuff around it: maybe compare to other models, maybe try other data sources.

**Review by akusok — APPROVED** [review]
Checked the files in "new" branch in main code base, it shows Jupyter notebooks correctly.
(can press the blue link saying "new" in PR and see how the code base looks like in the branch).
Good work!

**Review by tamiratGit — COMMENTED** [review]
unneccesary

**Review by tamiratGit — COMMENTED** [review]
some cleaning thing

**Review by tamiratGit — COMMENTED** [review]
cleanning

**Pull request merged**
